NOISSUE: Add Group-based Access Control to charts and update dependencies version
absmach/devops pull request #127
Opened 2023-06-19 06:47 UTC by arvindh123

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
```
This PR updates the Group-based access control mainflux components  users and things , removes auth and keto from charts 
And also updates the charts  dependencies version 
```
This PR branch is created from PR #125 

### Which issue(s) does this PR fix/relate to?

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-06-19 09:12 UTC, dborovcanin requested changes
Please fill out the template correctly and resolve conflicts.

2023-06-21 08:44 UTC, kibahop commented
Could you please create a contributing guide for **this** repo instead of pointing to another repo. Also my [PR](https://github.com/mainflux/devops/pull/125) was closed in favour of this PR, so do you expect me to continue with this PR? The helm chart should work reliably with current (1.25+) Kubernetes, or do you disagree with this?

2023-06-30 06:11 UTC, arvindh123 commented
> There is probably no need for new guidelines, but we should update the README with a link to the existing one. I think no actions from you, @arvindh123 included your work in this PR. Right, @arvindh123?

yes @dborovcanin, Included @kibahop changes in this PR 
And  it ready for review

2023-07-07 13:20 UTC, dborovcanin requested changes

2023-07-07 13:20 UTC, dborovcanin commented on charts/mainflux/templates/_helpers.tpl
> +{{- end -}}
Add an empty line.

2023-07-07 13:20 UTC, dborovcanin commented on charts/mainflux/templates/ingress.yaml
> +  namespace: default
Same.

2023-07-07 13:20 UTC, dborovcanin commented on charts/mainflux/values.yaml
> +    tag: "1.19.1-alpine"
Same.

2023-07-07 13:20 UTC, dborovcanin commented on charts/mainflux/values.yaml
> +    #   - {}
Remove commented code.

2024-08-12 08:49 UTC, dborovcanin reviewed
@JeffMboya Please review this PR.

2024-08-13 14:55 UTC, JeffMboya commented
> @JeffMboya Please review this PR.

LGTM

2024-08-14 05:54 UTC, JeffMboya requested changes

2024-08-14 05:54 UTC, JeffMboya commented on charts/mainflux/templates/timescale-reader-deployment.yaml
> +# Copyright (c) Mainflux
```suggestion
# Copyright (c) Abstract Machines
```

2024-08-14 05:54 UTC, JeffMboya commented on charts/mainflux/templates/timescale-writer-deployment.yaml
> +  # Copyright (c) Mainflux
```suggestion
# Copyright (c) Abstract Machines
```

2024-08-27 10:09 UTC, JeffMboya commented on charts/mainflux/values.yaml
> +  # sendTelemetry: true
> Why do we have there and some other values commented? It results in errors such as `nil pointer evaluating interface {}.pullSecrets`?

@dborovcanin this is in reference to this issue: [https://github.com/absmach/devops/issues/136](url)

2024-08-27 10:13 UTC, dborovcanin approved these changes

2024-08-27 10:13 UTC, merged