MG-141 - Bootstrap and Certs service are not starting properly in k8s setup with HELM
absmach/devops pull request #152
Opened 2024-09-22 07:32 UTC by JeffMboya

### What does this do?
This pull fixes helm charts to make sure Bootstrap and Certs services start correctly when deploying Magistrala using Helm in a Kubernetes environment. 

### Which issue(s) does this PR fix/relate to?
- Resolves #141 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2024-09-25 11:18 UTC, arvindh123 requested changes
Getting this error from journal service 
```log 
"2024-09-25T11:16:36.613218962Z","level":"ERROR","msg":"failed to apply migrations : failed to connect to `user=magistrala database=journal`:\n\t127.0.0.1:5432 (localhost): dial error: dial tcp 127.0.0.1:5432: connect: connection refused\n\t[::1]:5432 (localhost): dial error: dial tcp [::1]:5432: connect: connection refused"}
```

2024-09-25 11:22 UTC, arvindh123 requested changes
```logs
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  14m                    default-scheduler  Successfully assigned mg/magistrala-cassandra-1 to mg-staginig-r9mqr
  Warning  Unhealthy  10m (x2 over 10m)      kubelet            Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: container is in CONTAINER_EXITED state
  Warning  Unhealthy  10m (x3 over 10m)      kubelet            Readiness probe errored: rpc error: code = Unknown desc = failed to exec in container: container is in CONTAINER_EXITED state
  Normal   Pulled     9m1s (x4 over 14m)     kubelet            Container image "cassandra:3.11.6" already present on machine
  Normal   Created    9m1s (x4 over 14m)     kubelet            Created container magistrala-cassandra
  Normal   Started    9m1s (x4 over 14m)     kubelet            Started container magistrala-cassandra
  Warning  Unhealthy  6m59s                  kubelet            Readiness probe errored: rpc error: code = NotFound desc = failed to exec in container: failed to create exec "c61d12dd0734ae81a7bfe08b65dbe7d6de441d4747aa494f090b4308a7e33ee8": container not created: not found
  Warning  Unhealthy  6m59s (x2 over 6m59s)  kubelet            Liveness probe errored: rpc error: code = NotFound desc = failed to exec in container: failed to load task: no running task found: task 538c107c2a50d5114e20e9a7313b4bdadeda32d71fec4979e453d3286f6b0e5a not found: not found
  Warning  Unhealthy  6m59s                  kubelet            Readiness probe errored: rpc error: code = NotFound desc = failed to exec in container: failed to load task: no running task found: task 538c107c2a50d5114e20e9a7313b4bdadeda32d71fec4979e453d3286f6b0e5a not found: not found
  Warning  BackOff    4m31s (x13 over 10m)   kubelet            Back-off restarting failed container magistrala-cassandra in pod magistrala-cassandra-1_mg(2a5732f6-6fb7-4c2e-8362-9cf8936c0001)
```

One of the cassandra pod is getting to error state

2024-09-25 16:00 UTC, arvindh123 approved these changes

2024-09-26 08:22 UTC, dborovcanin commented on charts/magistrala/Chart.yaml
> +    email: drasko.draskovic@abstractmachines.fr
@arvindh123 Please add your info here as well.

2024-09-26 08:25 UTC, dborovcanin approved these changes

2024-09-26 08:26 UTC, merged