MG-154 - Jaeger Cassandra pods are not stable
absmach/devops pull request #155
Opened 2024-09-26 12:38 UTC by JeffMboya

### What does this do?
This pull request updates configuration parameters for Jaeger with Cassandra as the storage backend to ensure that the Cassandra pods remain stable and healthy

### Which issue(s) does this PR fix/relate to?
- Resolves #154

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2024-09-30 06:55 UTC, arvindh123 requested changes

2024-09-30 06:55 UTC, arvindh123 commented on charts/magistrala/values.yaml
> +      keyspace: jaeger_v1
Do we need this ? 
I think this for externally provisioned cassandra

2024-09-30 06:55 UTC, arvindh123 commented on charts/magistrala/values.yaml
> +      endpoint_snitch: GossipingPropertyFileSnitch
Do we need this ? I think this for externally provisioned cassandra

2024-09-30 06:55 UTC, arvindh123 requested changes

2024-09-30 06:55 UTC, arvindh123 commented on charts/magistrala/values.yaml
> -  collector:
Why collector configuration is removed

2024-10-01 07:17 UTC, arvindh123 approved these changes

2024-10-01 09:38 UTC, dborovcanin approved these changes

2024-10-01 09:38 UTC, merged