NOISSUE - Fix chart directory in `lint-test.yaml`
absmach/devops pull request #156
Opened 2024-10-01 14:39 UTC by JeffMboya

### What does this do?

This pull request fixes the issue where the provided chart directory was not being detected as a valid Helm chart directory during the `ct lint` step in the GitHub CI workflow.

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

```bash
Run ct lint --target-branch main --chart-dirs charts/amdm --debug
Linting charts...
>>> helm version --template {{ .Version }}
>>> git rev-parse --is-inside-work-tree
>>> git rev-parse --verify origin/main
>>> git merge-base origin/main HEAD
>>> git diff --find-renames --name-only 277fe28b0343dafe56e8be88a69f5c8eec649e[18](https://github.com/absmach/amdm/actions/runs/11127502755/job/30919951217?pr=103#step:9:19) -- charts/amdm
Directory "charts/amdm" is not a valid chart directory. Skipping...
Directory "charts/amdm" is not a valid chart directory. Skipping...
Directory "charts/amdm" is not a valid chart directory. Skipping...
Directory "charts/amdm" is not a valid chart directory. Skipping...
Directory "charts/amdm" is not a valid chart directory. Skipping...
Directory "charts/amdm/charts" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm/templates" is not a valid chart directory. Skipping...
Directory "charts/amdm" is not a valid chart directory. Skipping...

2024-10-08 09:33 UTC, arvindh123 requested changes

2024-10-08 09:33 UTC, arvindh123 commented on charts/magistrala/README.md
> +| jaeger.collector.service.otlp.grpc.port | int | `4317` |  |
@JeffMboya Why do we need this values ? 
Just asking to know the usage of values

2024-10-08 09:42 UTC, JeffMboya commented on charts/magistrala/README.md
> +| jaeger.collector.service.otlp.grpc.port | int | `4317` |  |
@arvindh123 They ensure that Jaeger is ready to receive and process this data over the gRPC protocol

2024-10-08 09:43 UTC, arvindh123 commented on charts/magistrala/README.md
> +| jaeger.collector.service.otlp.grpc.port | int | `4317` |  |
Got it , Thank you

2024-10-08 10:14 UTC, arvindh123 approved these changes

2024-10-10 11:01 UTC, dborovcanin approved these changes

2024-10-10 11:01 UTC, merged